<a href="https://colab.research.google.com/github/sak1b0/Contest_Arena/blob/master/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
import pandas as pd
import numpy as np

url='https://raw.githubusercontent.com/sak1b0/Thesis/master/led7digit.csv'

data=pd.read_csv(url,header=None)

data=np.asarray(data)

X, y = np.split(data,[-1],axis=1)

#X=np.asarray(X)
#y=np.asarray(y)

print(data.shape)
print(X.shape)
print(y.shape)

model = MultinomialNB()
model.fit(X,y)
expected = y
predicted = model.predict(X)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

(500, 8)
(500, 7)
(500, 1)
              precision    recall  f1-score   support

         0.0       0.82      0.73      0.78        45
         1.0       0.76      0.59      0.67        37
         2.0       0.83      0.75      0.78        51
         3.0       0.63      0.75      0.69        57
         4.0       0.96      0.85      0.90        52
         5.0       0.78      0.87      0.82        52
         6.0       0.78      0.81      0.79        47
         7.0       0.79      0.65      0.71        57
         8.0       0.65      0.64      0.65        53
         9.0       0.57      0.76      0.65        49

   micro avg       0.74      0.74      0.74       500
   macro avg       0.76      0.74      0.74       500
weighted avg       0.75      0.74      0.74       500

[[33  0  0  1  0  0  2  0  6  3]
 [ 0 22  1  5  1  0  0  8  0  0]
 [ 0  0 38  7  0  0  2  0  3  1]
 [ 0  0  0 43  1  2  0  2  2  7]
 [ 0  0  0  0 44  2  0  0  0  6]
 [ 0  0  0  2  0 45  2  0  0  3]
 [ 1  0  0  0  0

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
